### ISSUE TITLE
python2.7 is being deprecated

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/snafu#103]
see this message from pip:

```
Step 11/14 : RUN pip install "elasticsearch>=6.0.0,<=7.0.2"
 ---> Running in 31c46c82647f
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```

It's time, right?  There are no platforms that we support that don't have python3 at this point, along with packages that we need, right?   for example, python3-elasticsearch RPM.

**Comment by aakarshg** [comment]
- [x] FIO
- [x] SmallFile
- [x] FS-drift
- [x] HammerDB
- [x] IPerf
- [x] Sysbench
- [x] Uperf
- [x] PGbench
- [ ] YCSB: The original project does support python3 yet

Most of them have been addressed by #108

**Comment by bengland2** [comment]
agreed.  And PR 108 merged, closing this issue.

**Comment by aakarshg** [comment]
Reopening this as YCSB wrapper hasn't yet been migrated to python3

**Comment by rsevilla87** [comment]
I think we can close this one @aakarshg
