### ISSUE TITLE
[RFE] Publish a pip package

### ISSUE THREAD

**Issue by aakarshg** [cloud-bulldozer/snafu#129]
Snafu needs to be published a python package to pip, to make it easier to install/upgrade and run. This will also put more emphasis on snafu being used independent of ripsaw.

**Comment by bengland2** [comment]
My caution here is that there is no way to run snafu really without ripsaw at this point.   Sure, you can run a single process on your laptop, but there is no mechanism for deploying pods on a set of hosts other than K8S.   I was going to add an issue for this but never got around to it.  If I was doing it, I'd suggest that for non-K8S environments we use ansible playbook to deploy snafu containers, run them like before, and then tear them down (like rally?).   The playbook would take the place of the K8S scheduler.   @acalhounRH what do you think?

**Comment by jtaleric** [comment]
Sure, today Ripsaw is the only tool taking advantage of snafu. The other benefit of the pip package would allow us to move the docker files to Rispaw, and merely update the pip install snafu to the latest version in the dockerfile.
