### ISSUE TITLE
BUG: Snafu CI only triggers a single benchmark test even if PR affects more

### ISSUE THREAD

**Issue by aakarshg** [cloud-bulldozer/snafu#152]
Have been noticing this oddity with snafu ci, where even if the PR changes more than a benchmark, only the first benchmark is run. 

Example PR: https://github.com/cloud-bulldozer/snafu/pull/151 this only ran fio, despite changes affecting dockerfiles of other benchmarks

**Comment by dry923** [comment]
I've noticed this myself as well. Working on it atm
