### ISSUE TITLE
fs-drift with cephfs ReadWriteMany : limit of total fields exceeded

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/snafu#72]
When I use fs-drift with cephfs and access_mode: ReadWriteMany, snafu fails to write results for at least 1 pod because of:
```
            "reason": "Limit of total fields [1000] in index [ripsaw-fs-drift-results-000001] has been exceeded", 
```
I think this is caused because all the pods are sharing the same directory tree (intentionally) and are thus seeing each others' output JSON and not filtering that.   Can be fixed by selecting just response time and JSON files that have a matching hostname (i.e. pod name).

**Comment by aakarshg** [comment]
This has been addressed with #83
